# Generated by Django 4.2.2 on 2023-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='evolution_type',
            field=models.CharField(choices=[('like', 'Цена понравилась'), ('dislike', 'Цена не понравилась')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price_per_square',
            field=models.FloatField(null=True),
        ),
    ]
