# Generated by Django 4.2.2 on 2023-06-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_user_apartment_price_user_evolution_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
    ]
