# Generated by Django 4.2.2 on 2023-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_user_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='floor',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='floor_count',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='living_space',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='metro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rooms_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_construction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='apartment_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_per_square',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
