# Generated by Django 4.2.2 on 2023-06-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_user_district_user_floor_user_floor_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_of_construction',
        ),
    ]
