# Generated by Django 4.2.2 on 2023-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_remove_user_year_of_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_of_construction',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
